creation_rules:
  - encrypted_regex: '^(latitude|longitude|external_url|db_url)$'
    path_regex: 'config/.*\.sops\.yaml$'
    age: >-
      age109fzapgarv59gpyu5tgmwgn7j3hwmfs0dhrz3lrqvjy046jxafnse30kvj
